title: Liz Lima
description: > # this means to ignore newlines until "baseurl:"
   I am master's student of computer science at San Pablo Catholic University (UCSP), Arequipa.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lizlima.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "https://twitter.com/slizlt" #if your site has a twitter account, enter it here

# Author Settings
author: Liz Lima # add your name
author-img: profile/lizlimaprofile.jpeg # add your photo
about-author:   I am master's student of computer science at San Pablo Catholic University (UCSP), Arequipa. # add description
social-twitter: slizlt # add your Twitter handle
social-facebook: rhiannonmarypayne # add your Facebook handle
social-github: LizLima # ig handle
social-linkedin: rhipayne # add your Linkedin handle
social-email: lizbethlima@gmail.com # add your Email address

# Disqus
discus-identifier: Liz Lima # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
